Repository Witekio/pluma-automation, pull requests merged in 2021-01, with the labels that each got.

#177 Expose power controllers reboot_delay in target config
  pluma/cli/targetconfig.py
  tests/generic/cli/test_TargetConfig.py
Labels: enhancement

#182 CI: Fetch git tags before attempting pypi push
  .github/workflows/bump-version-and-publish-to-pypi.yml
Labels: bug

#189 CI: ignore static check error until it passes
  .github/workflows/static-types.yml
Labels: unit tests

#194 Makefile: add validate and scope for test cmd
  Makefile
  README.md
Labels: documentation, unit tests
